# Generated by Django 6.0.4 on 2026-04-08 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Korte beschrijving')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Featured afbeelding')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('live_url', models.URLField(blank=True, verbose_name='Live URL')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Uitgelicht?')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projecten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Pagina Titel')),
                ('slug', models.SlugField(verbose_name='Pagina Slug')),
                ('content_markdown', models.TextField(help_text='Schrijf hier je content in Markdown', verbose_name='Content (Markdown)')),
                ('content_html', models.TextField(editable=False, verbose_name='Content (HTML)')),
                ('order', models.IntegerField(default=0, verbose_name='Volgorde')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Pagina',
                'verbose_name_plural': "Project Pagina's",
                'ordering': ['order', 'created_at'],
                'unique_together': {('project', 'slug')},
            },
        ),
    ]
