# Generated by Django 6.0.4 on 2026-04-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.CharField(blank=True, choices=[('', '— Geen afbeelding —'), ('images/tor-relay.svg', 'Tor Relay'), ('images/hack-the-box.svg', 'Hack The Box'), ('images/boot-dev.svg', 'Boot.dev'), ('images/portfolio.svg', 'Portfolio Site')], default='', help_text='Kies een afbeelding uit de lijst (pad is relatief aan static/images/).', max_length=200, null=True, verbose_name='Featured afbeelding'),
        ),
    ]
