# Generated by Django 6.0.4 on 2026-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_html',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Description (HTML)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description (Markdown)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.CharField(blank=True, choices=[('', '— Geen afbeelding —'), ('images/tor-relay.svg', 'Tor Relay'), ('images/hack-the-box.svg', 'Hack The Box'), ('images/boot-dev.svg', 'Boot.dev'), ('images/portfolio.svg', 'Portfolio Site')], default='', help_text='Choose an image from the list (path is relative to static/images/).', max_length=200, null=True, verbose_name='Featured image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
