# Generated by Django 6.0.4 on 2026-04-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_description_html_alter_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_markdown', models.TextField(help_text='Verschijnt op de homepage. Schrijf in Markdown.', verbose_name='Introductie (Markdown)')),
                ('intro_html', models.TextField(blank=True, default='', editable=False, verbose_name='Introductie (HTML)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Introductie',
                'verbose_name_plural': 'Site Introductie',
            },
        ),
    ]
