# Generated by Django 6.0.4 on 2026-05-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_siteintro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteintro',
            options={'verbose_name': 'Site Introduction', 'verbose_name_plural': 'Site Introduction'},
        ),
        migrations.AlterField(
            model_name='siteintro',
            name='intro_html',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Introduction (HTML)'),
        ),
        migrations.AlterField(
            model_name='siteintro',
            name='intro_markdown',
            field=models.TextField(help_text='Appears at the top of the homepage. Write in Markdown.', verbose_name='Introduction (Markdown)'),
        ),
    ]
